
- name: "Gluu Cluster - OpenLDAP - listen for external IP"
  lineinfile:
    path: /opt/gluu-server-{{ gluu_version }}/opt/symas/etc/openldap/symas-openldap.conf
    regexp: '^HOST_LIST=".*'
    line: 'HOST_LIST="ldaps://127.0.0.1:1636/ ldaps://{{ gluu_ip }}:1636/"'

- name: "Gluu Cluster - OpenLDAP - Update ExtraArgs"
  lineinfile:
    path: /opt/gluu-server-{{ gluu_version }}/opt/symas/etc/openldap/symas-openldap.conf
    regexp: '^EXTRA_SLAPD_ARGS="'
    line: 'EXTRA_SLAPD_ARGS="-F /opt/symas/etc/openldap/slapd.d"'
  when: gluu_cluster_ldap_replication and not gluu_cluster_ldap_replication_without_cluster_manager

- name: "Gluu Cluster - OpenLDAP - Replication"
  block:
    - name: Check if LDAP replication is already setup
      stat:
        path: /opt/gluu-server-{{ gluu_version }}/opt/gluu/data/accesslog_db
      register: ldap_replication_is_setup

    - name: "Gluu Cluster - OpenLDAP - Create accesslog_db directory"
      file:
        path: '/opt/gluu-server-{{ gluu_version }}/opt/gluu/data/accesslog_db'
        state: directory
        
    - name: "Gluu Cluster - OpenLDAP - Update permission directory"
      command: '{{ gluu_container_command }} "chown -R ldap /opt/gluu/data/"'
        
    - name: "Gluu Cluster - OpenLDAP - Stop LDAP server"
      command: '{{ gluu_container_command }} "service solserver stop"'

    - name: "Gluu Cluster - OpenLDAP - Copy new slapd.conf file"
      template:
        src: cluster/slapd.conf.j2
        dest: /opt/gluu-server-{{ gluu_version }}/opt/symas/etc/openldap/slapd.conf

    - name: "Gluu Cluster - OpenLDAP - Create ldap.conf file"
      file:
        path: /opt/gluu-server-{{ gluu_version }}/opt/symas/etc/openldap/ldap.conf
        state: touch

    - name: "Gluu Cluster - OpenLDAP - Allow self-signed certificate"
      lineinfile:
        path: /opt/gluu-server-{{ gluu_version }}/opt/symas/etc/openldap/ldap.conf
        regexp: '^TLS_REQCERT '
        line: 'TLS_REQCERT never'

    - name: "Gluu Cluster - OpenLDAP - Add self-signed certificate"
      lineinfile:
        path: /opt/gluu-server-{{ gluu_version }}/opt/symas/etc/openldap/ldap.conf
        regexp: '^TLS_CACERT '
        line: 'TLS_CACERT /etc/certs/openldap.pem'

    - name: "Gluu Cluster - OpenLDAP - Start LDAP server"
      command: '{{ gluu_container_command }} "service solserver start"'
  when: gluu_cluster_ldap_replication and gluu_cluster_ldap_replication_without_cluster_manager